category: GAMES_AND_TRIVIA
defaultLocale: pt-BR
localizedSettings:
  developerEmail: alencar.lucas.a@gmail.com
  developerName: Lucas Alencar
  displayName: O Barista
  fullDescription: A personal barista that helps you make coffee
  pronunciation: O Barista
  shortDescription: A personal barista that helps you make coffee
  voice: female_1
projectId: barista-3b2b6
