category: GAMES_AND_TRIVIA
defaultLocale: en
localizedSettings:
  developerEmail:
  developerName:
  displayName: Hello world sample
  fullDescription:
  privacyPolicyUrl:
  pronunciation: Hello world sample
  shortDescription:
  smallLogoImage:
  termsOfServiceUrl:
projectId: <PROJECT_ID>
